### ISSUE TITLE
Agents do not work autonomously.

### ISSUE THREAD

**Issue by yuuuuuuuuri** [vlandlive/scene-based-generative-agent#2]
Please excuse my question.
I generated an agent by running this code, but no matter how much I run it, the agent only speaks the same lines.
Maybe the code below is not executed and hasOthers is not set to True.

`if pid != self.playerInfo["pid"] and pid in agentData:
            observation += agentData[pid]["name"] + ", "
            hasOthers = True
 `

Sorry for the newbie question, but how do I set up the agent to run autonomously?

**Comment by celineycn** [comment]
Hi @yuuuuuuuuri , would you mind join our discord? so we can communicate efficiently to help solving your problem. our discord group: https://discord.com/invite/6Nb9VQP67m

**Comment by yuuuuuuuuri** [comment]
I will join the discord!
Thanks for answering!

**Comment by geoxxu** [comment]
resolved
